package com.film.one;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import com.bumptech.glide.Glide;import java.util.*;

public class MainActivity extends Activity {
    static final int BG=Color.rgb(7,9,14),PANEL=Color.rgb(18,21,29),WHITE=Color.WHITE,MUTED=Color.rgb(158,166,180),BLUE=Color.rgb(0,174,255);
    LinearLayout body,bottom; EditText search; int currentTab=0; CatalogRepository repo; SharedPreferences prefs; ArrayList<Movie> visible=new ArrayList<>(); Map<String,Integer> sectionPages=new HashMap<>();
    public static class Movie {
        String tmdbId,id,type,title,originalTitle,year,genre,rating,overview,poster,backdrop,videoUrl,runtime;
        ArrayList<String> audio=new ArrayList<>(), subtitles=new ArrayList<>();
        static Movie fromJson(JSONObject o)throws Exception{Movie m=new Movie();m.tmdbId=o.optString("tmdb_id",o.optString("id"));m.id=o.optString("id",m.tmdbId);m.type=o.optString("type","movie");m.title=o.optString("title",o.optString("name"));m.originalTitle=o.optString("original_title",o.optString("original_name"));m.year=o.optString("year",o.optString("release_date",o.optString("first_air_date")));if(m.year.length()>4)m.year=m.year.substring(0,4);m.genre=o.optString("genre","");m.rating=String.valueOf(o.optDouble("rating",o.optDouble("vote_average",0)));m.overview=o.optString("overview",o.optString("description","Описание пока недоступно."));m.poster=o.optString("poster","");m.backdrop=o.optString("backdrop","");m.videoUrl=o.optString("video_url","");m.runtime=o.optString("runtime","");JSONArray aa=o.optJSONArray("audio");if(aa!=null)for(int i=0;i<aa.length();i++)m.audio.add(aa.optString(i));JSONArray ss=o.optJSONArray("subtitles");if(ss!=null)for(int i=0;i<ss.length();i++)m.subtitles.add(ss.optString(i));return m;}
        JSONObject toJson(){JSONObject o=new JSONObject();try{o.put("tmdb_id",tmdbId);o.put("id",id);o.put("type",type);o.put("title",title);o.put("original_title",originalTitle);o.put("year",year);o.put("genre",genre);o.put("rating",rating);o.put("overview",overview);o.put("poster",poster);o.put("backdrop",backdrop);o.put("video_url",videoUrl);}catch(Exception ignored){}return o;}
    }
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);prefs=getSharedPreferences("film_one",MODE_PRIVATE);String index=getAsset("catalog_index_url","https://film-one.github.io/film-one/catalog/index.json");String api=getAsset("api_base_url","");repo=new CatalogRepository(this,index,api);build();repo.loadIndex(x->runOnUiThread(()->{if(x==null){showError("Не удалось загрузить каталог");return;}showHome();}));}
    String getAsset(String k,String def){try{JSONObject o=new JSONObject(readAsset("config.json"));return o.optString(k,def);}catch(Exception e){return def;}}
    String readAsset(String n)throws Exception{java.io.InputStream in=getAssets().open(n);java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();byte[]b=new byte[4096];int z;while((z=in.read(b))!=-1)o.write(b,0,z);return o.toString("UTF-8");}
    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setPadding(dp(18),dp(8),dp(14),dp(8));TextView logo=tv("film.one",25,WHITE);logo.setTypeface(null,1);top.addView(logo,new LinearLayout.LayoutParams(0,dp(58),1));TextView s=tv("⌕",31,WHITE);s.setGravity(17);top.addView(s,new LinearLayout.LayoutParams(dp(54),dp(58)));s.setOnClickListener(v->focusSearch());root.addView(top);ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),0,dp(16),dp(24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(68)));setContentView(root);buildNav();}
    void buildNav(){bottom.removeAllViews();String[] labels={"⌂\nГлавная","▦\nКаталог","♡\nМоё","⚙\nНастройки"};for(int i=0;i<4;i++){final int k=i;TextView t=tv(labels[i],11,i==currentTab?WHITE:MUTED);t.setGravity(17);bottom.addView(t,new LinearLayout.LayoutParams(0,dp(64),1));t.setOnClickListener(v->{currentTab=k;buildNav();if(k==0)showHome();else if(k==1)showCatalog();else if(k==2)showFavorites();else showSettings();});}}
    void heading(String s,String sub){TextView h=tv(s,28,WHITE);h.setTypeface(null,1);body.addView(h,new LinearLayout.LayoutParams(-1,dp(45)));if(sub!=null)body.addView(tv(sub,13,MUTED),new LinearLayout.LayoutParams(-1,dp(30)));}
    void addSearch(){search=new EditText(this);search.setSingleLine(true);search.setTextColor(WHITE);search.setHintTextColor(MUTED);search.setHint("Поиск фильма или сериала");search.setPadding(dp(18),0,dp(18),0);search.setBackground(bg(PANEL,24));body.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)search.getLayoutParams();p.setMargins(0,0,0,dp(14));search.setLayoutParams(p);search.setOnEditorActionListener((v,a,e)->{runSearch(search.getText().toString().trim());return true;});}
    void focusSearch(){if(search==null)showHome();search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);}
    void showHome(){body.removeAllViews();heading("Фильмы и сериалы","Каталог обновляется автоматически");addSearch();visible.clear();sectionPages.clear();for(CatalogRepository.Section s:repo.sections()){if(s.id.equals("new_movies")||s.id.equals("popular_movies")||s.id.equals("popular_tv")||s.id.equals("top_movies")||s.id.equals("top_tv"))loadSection(s,1,true);}genres();}
    void showCatalog(){body.removeAllViews();heading("Каталог","Постраничная загрузка — без загрузки десятков тысяч записей сразу");addSearch();sectionPages.clear();for(CatalogRepository.Section s:repo.sections())loadSection(s,1,true);}
    void loadSection(CatalogRepository.Section s,int page,boolean append){repo.loadSection(s,page,list->{runOnUiThread(()->{if(list.isEmpty())return;visible.addAll(list);sectionPages.put(s.id,page);section(s.title,page,list);});});}
    void section(String name,int page,List<Movie> list){
        LinearLayout block=new LinearLayout(this);block.setOrientation(LinearLayout.VERTICAL);
        TextView h=tv(name+(page>1?"  •  страница "+page:""),19,WHITE);h.setTypeface(null,1);block.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));
        HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);row.setPadding(0,0,0,dp(4));for(Movie m:list)row.addView(card(m));hs.addView(row);block.addView(hs,new LinearLayout.LayoutParams(-1,dp(226)));
        if(page < 500){Button more=new Button(this);more.setText("Показать ещё");more.setTextColor(WHITE);more.setBackground(bg(Color.rgb(24,40,58),18));more.setOnClickListener(v->{more.setEnabled(false);int next=page+1;CatalogRepository.Section target=null;for(CatalogRepository.Section x:repo.sections())if(x.title.equals(name)){target=x;break;}if(target!=null)loadSection(target,next,true);});block.addView(more,new LinearLayout.LayoutParams(-1,dp(48)));}
        body.addView(block);
    }
    View card(Movie m){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(6),dp(6),dp(6),dp(6));c.setBackground(bg(PANEL,16));ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(bg(Color.rgb(35,39,49),12));if(!m.poster.isEmpty())Glide.with(this).load(m.poster).centerCrop().placeholder(android.R.drawable.ic_menu_gallery).error(android.R.drawable.ic_menu_report_image).into(image);c.addView(image,new LinearLayout.LayoutParams(dp(142),dp(164)));TextView title=tv(m.title,13,WHITE);title.setMaxLines(2);title.setPadding(dp(2),dp(5),dp(2),0);c.addView(title,new LinearLayout.LayoutParams(dp(142),dp(40)));TextView meta=tv("★ "+shortRating(m.rating)+"  •  "+m.year,11,MUTED);c.addView(meta,new LinearLayout.LayoutParams(dp(142),dp(22)));c.setOnClickListener(v->openDetails(m));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(154),dp(232));cp.setMargins(0,0,dp(10),0);c.setLayoutParams(cp);return c;}
    String shortRating(String s){try{return String.format(Locale.US,"%.1f",Double.parseDouble(s));}catch(Exception e){return s;}}
    void genres(){List<String>g=repo.genres();if(g.isEmpty())return;TextView h=tv("Жанры",19,WHITE);h.setTypeface(null,1);body.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);for(String x:g){TextView chip=tv(x,13,WHITE);chip.setGravity(17);chip.setPadding(dp(14),0,dp(14),0);chip.setBackground(bg(Color.rgb(24,40,58),20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(40));p.setMargins(0,0,dp(8),0);row.addView(chip,p);}hs.addView(row);body.addView(hs,new LinearLayout.LayoutParams(-1,dp(52)));}
    void runSearch(String q){if(q.isEmpty())return;body.removeAllViews();heading("Поиск","Результаты: "+q);TextView loading=tv("Поиск…",15,MUTED);body.addView(loading,new LinearLayout.LayoutParams(-1,dp(70)));repo.search(q,list->runOnUiThread(()->{body.removeAllViews();heading("Поиск","Результаты: "+q);if(list.isEmpty()){body.addView(tv("Ничего не найдено.",15,MUTED));return;}section("Результаты",1,list);}));}
    void showFavorites(){body.removeAllViews();heading("Моё","Избранное и история просмотра");try{JSONArray a=new JSONArray(prefs.getString("favorite_items","[]"));ArrayList<Movie> list=new ArrayList<>();for(int i=0;i<a.length();i++)list.add(Movie.fromJson(a.getJSONObject(i)));if(list.isEmpty())body.addView(tv("♡  В избранном пока ничего нет.",15,MUTED),new LinearLayout.LayoutParams(-1,dp(70)));else section("Избранное",1,list);}catch(Exception e){body.addView(tv("Не удалось открыть избранное.",15,MUTED));}String history=prefs.getString("history","");if(!history.isEmpty())body.addView(tv("История просмотра\n"+history,14,MUTED),new LinearLayout.LayoutParams(-1,dp(120)));}
    void showSettings(){body.removeAllViews();heading("Настройки","film.one");String[]a={"Язык\nРусский","Качество видео\nАвтоматически","Автовоспроизведение\nВключено","Субтитры\nАвтоматически","Очистить историю","О приложении\nfilm.one\nTMDB metadata & artwork attribution"};for(String s:a){TextView t=tv(s,15,WHITE);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(16),0,dp(12),0);t.setBackground(bg(PANEL,14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,0,0,dp(8));body.addView(t,p);if(s.equals("Очистить историю"))t.setOnClickListener(v->{prefs.edit().remove("history").apply();Toast.makeText(this,"История очищена",Toast.LENGTH_SHORT).show();});}}
    void openDetails(Movie m){Intent i=new Intent(this,DetailActivity.class);i.putExtra("movie",m.toJson().toString());startActivity(i);}
    void showError(String s){body.removeAllViews();heading("Каталог недоступен",null);body.addView(tv(s+"\n\nПроверь URL каталога в config.json.",15,MUTED));}
    @Override protected void onDestroy(){repo.close();super.onDestroy();}
}
