package com.film.one;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.content.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;

public class MainActivity extends Activity {
 static final int BG=Color.rgb(7,7,9),PANEL=Color.rgb(20,20,23),WHITE=Color.WHITE,MUTED=Color.rgb(160,160,168),RED=Color.rgb(229,9,20);
 LinearLayout root,body,bottom; EditText search; ArrayList<Movie> movies=new ArrayList<>(); HashSet<String> favorites=new HashSet<>(); int currentTab=0; String catalogUrl="";
 static class Movie {String id,title,year,genre,rating,type,poster,description,video; Movie(){} Movie(JSONObject o)throws Exception{id=o.optString("id");title=o.optString("title");year=o.optString("year");genre=o.optString("genre");rating=o.optString("rating");type=o.optString("type","movie");poster=o.optString("poster");description=o.optString("description");video=o.optString("video_url");}}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);loadConfig();build();loadRemoteCatalog();}
 void loadConfig(){try{InputStream in=getAssets().open("config.json");String s=read(in);catalogUrl=new JSONObject(s).optString("catalog_url");}catch(Exception e){}}
 String read(InputStream in)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);return o.toString("UTF-8");}
 void loadRemoteCatalog(){if(catalogUrl.isEmpty()||catalogUrl.contains("YOUR-DOMAIN")){loadDemo();showHome();return;} new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(catalogUrl).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestMethod("GET");String s=read(c.getInputStream());JSONObject root=new JSONObject(s);JSONArray a=root.optJSONArray("items");ArrayList<Movie> list=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++)list.add(new Movie(a.getJSONObject(i)));runOnUiThread(()->{movies.clear();movies.addAll(list);showHome();});}catch(Exception e){runOnUiThread(()->{loadDemo();showHome();Toast.makeText(this,"Не удалось обновить каталог",Toast.LENGTH_SHORT).show();});}}).start();}
 void loadDemo(){movies.clear();try{String s=read(getAssets().open("../catalog.json"));}catch(Exception ignored){} movies.add(new MovieSafe("demo-1","Последний горизонт","2026","Фантастика","8.4","movie"));movies.add(new MovieSafe("demo-2","Ночной сигнал","2026","Ужасы","8.0","movie"));movies.add(new MovieSafe("demo-3","Колония","2025","Драма","7.7","series"));}
 MovieSafe movie(String id,String t,String y,String g,String r,String type){return new MovieSafe(id,t,y,g,r,type);}
 class MovieSafe extends Movie{MovieSafe(String id,String t,String y,String g,String r,String type){super();this.id=id;title=t;year=y;genre=g;rating=r;this.type=type;poster="";description="Описание появится из online каталога.";video="";}}
 TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} void margin(View v,int l,int t,int r,int b){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setPadding(dp(18),dp(8),dp(14),dp(8));TextView logo=tv("film.one",24,WHITE);logo.setTypeface(null,1);top.addView(logo,new LinearLayout.LayoutParams(0,dp(58),1));TextView s=tv("⌕",30,WHITE);s.setGravity(17);top.addView(s,new LinearLayout.LayoutParams(dp(52),dp(58)));s.setOnClickListener(v->focusSearch());root.addView(top);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),0,dp(16),dp(20));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setGravity(17);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(68)));setContentView(root);buildNav();}
 void buildNav(){bottom.removeAllViews();String[] l={"⌂\nГлавная","▦\nКаталог","♡\nМоё","⚙\nНастройки"};for(int i=0;i<4;i++){final int k=i;TextView t=tv(l[i],11,i==currentTab?WHITE:MUTED);t.setGravity(17);bottom.addView(t,new LinearLayout.LayoutParams(0,dp(62),1));t.setOnClickListener(v->{currentTab=k;buildNav();if(k==0)showHome();else if(k==1)showCatalog();else if(k==2)showFavorites();else showSettings();});}}
 void title(String s,String sub){TextView h=tv(s,27,WHITE);h.setTypeface(null,1);body.addView(h,new LinearLayout.LayoutParams(-1,dp(44)));if(sub!=null)body.addView(tv(sub,13,MUTED),new LinearLayout.LayoutParams(-1,dp(34)));}
 void addSearch(){search=new EditText(this);search.setSingleLine();search.setTextColor(WHITE);search.setHintTextColor(Color.rgb(115,115,120));search.setHint("Поиск фильма или сериала");search.setBackground(bg(PANEL,24));body.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));margin(search,0,0,0,16);search.setOnEditorActionListener((v,a,e)->{showSearch(search.getText().toString());return true;});}
 void focusSearch(){if(search==null)showHome();search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);}
 ArrayList<Movie> filter(String type){ArrayList<Movie>x=new ArrayList<>();for(Movie m:movies)if(type.equals(m.type))x.add(m);return x;}
 void section(String name,List<Movie> list){TextView h=tv(name,19,WHITE);h.setTypeface(null,1);body.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);for(Movie m:list)row.addView(card(m));hs.addView(row);body.addView(hs,new LinearLayout.LayoutParams(-1,dp(210)));}
 View card(Movie m){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(8),dp(8),dp(8),dp(6));c.setBackground(bg(PANEL,14));TextView p=tv("▶\n\n"+m.title,14,WHITE);p.setGravity(17);p.setTypeface(null,1);p.setBackground(bg(Color.rgb(42,42,47),12));c.addView(p,new LinearLayout.LayoutParams(dp(142),dp(132)));c.addView(tv("★ "+m.rating+"  •  "+m.year,11,MUTED),new LinearLayout.LayoutParams(dp(142),dp(30)));c.setOnClickListener(v->details(m));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(158),dp(182));cp.setMargins(0,0,dp(10),0);c.setLayoutParams(cp);return c;}
 void showHome(){body.removeAllViews();title("Фильмы и сериалы","Каталог обновляется из интернета");addSearch();section("Новые фильмы",movies);section("Сериалы",filter("series"));}
 void showCatalog(){body.removeAllViews();title("Каталог","Фильмы, сериалы и новые релизы");addSearch();section("Все",movies);section("Фильмы",filter("movie"));section("Сериалы",filter("series"));}
 void showSearch(String q){body.removeAllViews();title("Поиск","Результаты: "+q);ArrayList<Movie>r=new ArrayList<>();for(Movie m:movies)if(m.title.toLowerCase().contains(q.toLowerCase())||m.genre.toLowerCase().contains(q.toLowerCase()))r.add(m);if(r.isEmpty())body.addView(tv("Ничего не найдено.",16,MUTED),new LinearLayout.LayoutParams(-1,dp(80)));else section("Результаты",r);}
 void showFavorites(){body.removeAllViews();title("Моё","Избранные фильмы и сериалы");ArrayList<Movie>r=new ArrayList<>();for(Movie m:movies)if(favorites.contains(m.id))r.add(m);if(r.isEmpty())body.addView(tv("Вы ещё ничего не добавили в избранное.",15,MUTED),new LinearLayout.LayoutParams(-1,dp(80)));else section("Избранное",r);}
 void showSettings(){body.removeAllViews();title("Настройки","film.one");String[]a={"🔄 Обновлять каталог при запуске","🌐 Источник каталога: online JSON","🔔 Уведомления","ℹ О приложении","Версия 1.0.0"};for(String s:a){TextView t=tv(s,16,WHITE);t.setPadding(dp(16),0,dp(12),0);t.setBackground(bg(PANEL,14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,0,0,dp(8));body.addView(t,p); if(s.startsWith("🛠")) t.setOnClickListener(v->showAdmin());}}

 void showAdmin(){
  body.removeAllViews(); title("Админ-панель","Поиск данных и добавление в online каталог");
  EditText q=new EditText(this); q.setSingleLine(); q.setHint("Название фильма или сериала"); q.setTextColor(WHITE); q.setHintTextColor(MUTED); q.setBackground(bg(PANEL,18)); body.addView(q,new LinearLayout.LayoutParams(-1,dp(52))); margin(q,0,0,0,10);
  EditText token=new EditText(this); token.setSingleLine(); token.setHint("Admin token"); token.setTextColor(WHITE); token.setHintTextColor(MUTED); token.setBackground(bg(PANEL,18)); body.addView(token,new LinearLayout.LayoutParams(-1,dp(52))); margin(token,0,0,0,10);
  Button find=new Button(this); find.setText("🔎 Найти данные"); body.addView(find,new LinearLayout.LayoutParams(-1,dp(52))); margin(find,0,0,0,16);
  TextView results=tv("Введите название и нажмите «Найти данные».\nДанные будут получены через ваш catalog-api.",14,MUTED); body.addView(results,new LinearLayout.LayoutParams(-1,dp(100)));
  find.setOnClickListener(v->adminSearch(q.getText().toString().trim(),token.getText().toString().trim(),results));
 }
 void adminSearch(String q,String token,TextView results){
  if(q.isEmpty()){results.setText("Введите название.");return;}
  results.setText("Ищу…"); new Thread(()->{try{
   String url=catalogUrl.replaceAll("/catalog\\.json$","")+"/api/search?q="+URLEncoder.encode(q,"UTF-8")+"&token="+URLEncoder.encode(token,"UTF-8");
   HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection(); c.setConnectTimeout(8000); c.setReadTimeout(12000); String s=read(c.getInputStream()); JSONArray arr=new JSONObject(s).optJSONArray("results");
   runOnUiThread(()->{body.removeAllViews(); title("Результаты поиска",q); if(arr==null||arr.length()==0){body.addView(tv("Ничего не найдено.",15,MUTED));return;} for(int i=0;i<arr.length();i++){try{JSONObject o=arr.getJSONObject(i); TextView r=tv((i+1)+". "+o.optString("title")+"  •  "+o.optString("year")+"  •  "+o.optString("type"),15,WHITE);r.setPadding(dp(14),0,dp(10),0);r.setBackground(bg(PANEL,14));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(64));rp.setMargins(0,0,0,dp(8));body.addView(r,rp);r.setOnClickListener(v->addFromSearch(o,token));}catch(Exception ignored){}} });
  }catch(Exception e){runOnUiThread(()->results.setText("Ошибка: "+e.getMessage()));}}).start();
 }
 void addFromSearch(JSONObject o,String token){
  EditText video=new EditText(this);video.setSingleLine();video.setHint("URL видео (необязательно)");video.setTextColor(WHITE);video.setHintTextColor(MUTED);video.setBackground(bg(PANEL,16));
  new AlertDialog.Builder(this).setTitle("Добавить в каталог").setMessage(o.optString("title")+"\n"+o.optString("year")+"\n"+o.optString("genre" )).setView(video).setNegativeButton("Отмена",null).setPositiveButton("Добавить",(d,w)->postAdd(o,video.getText().toString().trim(),token)).show();
 }
 void postAdd(JSONObject o,String video,String token){new Thread(()->{try{
  o.put("video_url",video); String url=catalogUrl.replaceAll("/catalog\\.json$","")+"/api/add?token="+URLEncoder.encode(token,"UTF-8"); HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection(); c.setDoOutput(true); c.setRequestMethod("POST"); c.setRequestProperty("Content-Type","application/json"); OutputStream out=c.getOutputStream();out.write(o.toString().getBytes("UTF-8"));out.close(); String s=read(c.getInputStream());runOnUiThread(()->Toast.makeText(this,"Добавлено в каталог",Toast.LENGTH_LONG).show()); loadRemoteCatalog();
  }catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Не удалось добавить: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
 void details(Movie m){Dialog d=new Dialog(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(bg(Color.rgb(15,15,17),22));TextView h=tv(m.title,25,WHITE);h.setTypeface(null,1);l.addView(h,new LinearLayout.LayoutParams(-1,dp(48)));l.addView(tv(m.year+" • "+m.genre+" • ★ "+m.rating,13,MUTED),new LinearLayout.LayoutParams(-1,dp(36)));l.addView(tv(m.description,14,WHITE),new LinearLayout.LayoutParams(-1,dp(120)));LinearLayout a=new LinearLayout(this);Button play=new Button(this);play.setText("▶ Смотреть");Button fav=new Button(this);fav.setText(favorites.contains(m.id)?"♥ Удалить":"♡ В избранное");a.addView(play,new LinearLayout.LayoutParams(0,dp(52),1));a.addView(fav,new LinearLayout.LayoutParams(0,dp(52),1));l.addView(a);play.setOnClickListener(v->{d.dismiss();player(m);});fav.setOnClickListener(v->{if(favorites.contains(m.id))favorites.remove(m.id);else favorites.add(m.id);fav.setText(favorites.contains(m.id)?"♥ Удалить":"♡ В избранное");});d.setContentView(l);d.show();if(d.getWindow()!=null)d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94f),-2);}
 void player(Movie m){body.removeAllViews();TextView b=tv("‹ Назад",16,WHITE);body.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->showHome());TextView p=tv("▶\n\n"+m.title+"\n\nПлеер",20,WHITE);p.setGravity(17);p.setBackground(bg(Color.BLACK,12));body.addView(p,new LinearLayout.LayoutParams(-1,dp(260)));body.addView(tv("\nИсточник: "+(m.video.isEmpty()?"не указан":m.video),14,MUTED));}
}
