plugins { id 'com.android.application' }

android {
    namespace 'com.film.one'
    compileSdk 35
    defaultConfig {
        applicationId 'com.film.one'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    
    dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.4.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
    implementation 'androidx.media3:media3-ui:1.4.1'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}
}
